services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/docker/prowlarr/data:/config
    ports:
      - 9696:9696
    dns:
      - 1.1.1.1
    restart: unless-stopped
