services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - /opt/docker/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /opt/docker/prometheus/data:/prometheus
    ports:
      - 9090:9090
    environment:
      - TZ=Europe/London
    user: "1000"
    networks:
      - monitoring
    restart: unless-stopped
