services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /opt/docker/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /opt/docker/prometheus/data:/prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
