services:
  homepage:
    build:
      context: https://github.com/itsbekas/homepage.git
      args:
        VITE_DONETICK_URL: ${VITE_DONETICK_URL}
        VITE_DONETICK_API_KEY: ${VITE_DONETICK_API_KEY}
        VITE_TODOIST_API_TOKEN: ${VITE_TODOIST_API_TOKEN}
    container_name: homepage
    restart: unless-stopped
    ports:
      - "3002:3000"
