services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /opt/docker/grafana/data:/var/lib/grafana
    user: "1000"
    networks:
      - monitoring
    restart: unless-stopped

# References
# https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#run-grafana-via-docker-compose
# https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/