services:
  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:latest
    container_name: cross-seed
    user: 1000:1000
    ports:
      - 2468:2468
    volumes:
      - /opt/docker/cross-seed/config:/config
      - /data:/data
    networks:
      - media
    command: daemon
    restart: unless-stopped
