services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/docker/jellyfin/library:/config
      - /data/media:/data/media
    ports:
      - 8096:8096
    dns:
      - 1.1.1.1
    restart: unless-stopped
