services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - /opt/docker/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - management
    restart: unless-stopped
