services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/docker/bazarr/config:/config
      - /data/media:/data/media
    ports:
      - 6767:6767
    networks:
      - media
    restart: unless-stopped