services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8012:8000/tcp # Control server
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      # QBittorrent ports
      - 6880:6880
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /opt/docker/gluetun/data:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      # Timezone for accurate log times
      - TZ=Europe/London
      # DNS
      - DOT_PROVIDERS=quad9
      # Port forwarding
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c '/usr/bin/wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:6880/api/v2/app/setPreferences 2>&1'
      - BLOCK_MALICIOUS=off # Disable unbound DNS resolver
    restart: unless-stopped

# References
# https://github.com/Chillsmeit/qBittorrent-ProtonVPN-Guide
