- name: Home
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday
    - size: full
      widgets:
        - type: custom-api
          title: Upcoming Events
          cache: 15m
          template: |
            {{
              $token := newRequest "https://oauth2.googleapis.com/token"
                | withHeader "Content-Type" "application/x-www-form-urlencoded"
                | withStringBody "client_id=${GOOGLE_CLIENT_ID}&client_secret=${GOOGLE_CLIENT_SECRET}&refresh_token=${GOOGLE_REFRESH_TOKEN}&grant_type=refresh_token"
                | getResponse
            }}

            {{ if ne $token.Response.StatusCode 200 }}
              <p>Failed to get token: {{ $token.Response.Status }}</p>
            {{ else }}
              {{ $accessToken := $token.JSON.String "access_token" }}
              {{ $nowtime := now | formatTime "rfc3339" }}
              {{ $future := offsetNow "720h" | formatTime "rfc3339" }}
              {{
                $events := newRequest "https://www.googleapis.com/calendar/v3/calendars/primary/events"
                  | withParameter "timeMin" $nowtime
                  | withParameter "timeMax" $future
                  | withParameter "singleEvents" "true"
                  | withParameter "orderBy" "startTime"
                  | withHeader "Authorization" (print "Bearer " $accessToken)
                  | getResponse
              }}

              {{ if ne $events.Response.StatusCode 200 }}
                <p>Failed to fetch events: {{ $events.Response.Status }}</p>
              {{ else }}
                <div>
                  {{ range $events.JSON.Array "items" }}
                  {{ $start := .String "start.dateTime" }}
                  {{ $end := .String "end.dateTime" }}
                  {{ $isAllDay := eq $start "" }}
                  {{ if $isAllDay }}
                    {{ $start = print (.String "start.date") | parseLocalTime "DateOnly" }}
                    {{ $end = print (.String "end.date") | parseLocalTime "DateOnly" }}
                  {{ else }}
                    {{ $start = $start | parseTime "rfc3339" }}
                    {{ $end = $end | parseTime "rfc3339" }}            
                  {{ end }}
                  {{ $startDateOnly := $start | formatTime "DateOnly" }}
                  {{ $endDateOnly := $end | formatTime "DateOnly" }}
                  {{ $isStartAndEndDateSame := eq $startDateOnly $endDateOnly }}

                  <div style="display: flex; flex-wrap: wrap; justify-content: space-between; align-items: flex-start;">
                    <a href="https://calendar.google.com/calendar/u/0" target="_blank" class="size-h1" style="text-align: left; width: 215px;">
                      {{ .String "summary" }}
                    </a>
                    <a href="https://calendar.google.com/calendar/u/0" target="_blank" class="size-h3" style="text-align: left;">
                      {{ $start | formatTime "Mon, Jan 2 · 3:04 PM" }} 
                      {{ if $isStartAndEndDateSame }}
                          - {{ $end | formatTime "3:04 PM" }}
                        {{ else }}
                          - {{ $end | formatTime "Mon, Jan 2 · 3:04 PM" }}
                      {{ end }}
                    </a>
                    <div class="color-primary size-h3" style="text-align: right; width: 75px;" {{ $start | toRelativeTime }}>
                    </div>
                  </div>
                {{ end }}
                </div>
              {{ end }}
            {{ end }}
        - type: markets
          markets:
            - symbol: VWCE.DE
              name: All-World
            - symbol: SXR8.DE
              name: S&P 500
            - symbol: EUNK.DE
              name: Europe
    - size: small
      widgets:
        - type: weather
          location: $WEATHER_LOCATION
          units: metric
          hour-format: 24h
