services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/London
    ports:
      - 8191:8191
    dns:
      - 1.1.1.1
    networks:
      - media
    restart: unless-stopped 
