services:
  influxdb:
    image: influxdb:3-core
    container_name: influxdb
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
      - type: bind
        source: /opt/docker/influxdb3/data
        target: /var/lib/influxdb3/data
      - type: bind
        source: /opt/docker/influxdb3/plugins
        target: /var/lib/influxdb3/plugins
    restart: unless-stopped

# References
# https://docs.influxdata.com/influxdb3/core/get-started/setup/#docker-compose-with-a-mounted-file-system-object-store
