services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/London
      - PORT=5055
      - NODE_OPTIONS='--dns-result-order=ipv4first'
    ports:
      - 5055:5055
    dns:
      - 1.1.1.1
    volumes:
      - /opt/docker/jellyseerr/appdata/config:/app/config
    networks:
      - media
    restart: unless-stopped
